version: '3.8'

services:
  app:
    image: node
    container_name: cicd-express
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm i && npm run start"
