version: '3.8'

services:
  app1:
    image: node
    container_name: cicd-express
    networks:
      - vps-nginx-conf_app_network
      # - app_network
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm i && npm run start"
