name: Nodejs CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Setup Node
        # uses: actions/setup-node@v1
        # with:
          # node-version: 18
      # - run: npm install
      # - run: npm run build
