name: Nodejs CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Setup Node
        # uses: actions/setup-node@v1
        # with:
          # node-version: 18
      # - run: npm install
      # - run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.AUTH_SSH }}
      -name: Deploy to VPS
       run: ssh -o StrictHostKeyChecking=no egor@185.250.44.151 'cd dev/cicd-node && git pull' 
